### ISSUE TITLE
Deploy FastAPI with Docker

### ISSUE THREAD

**Issue by Deadshot1611** [Deadshot1611/Emojinator#9]
Create a Dockerfile to containerize the FastAPI backend and deploy it.
note: only to be done after.html file has been created

**Comment by geekyharsh05** [comment]
@Deadshot1611 Can you please assign this to me?

**Comment by Deadshot1611** [comment]
> @Deadshot1611 Can you please assign this to me?

I have assigned this to you  @geekyharsh05 . You can connect fastAPI for now but don't deploy until the html file is fully ready.

**Comment by geekyharsh05** [comment]
@Deadshot1611 Where it the fastapi code?? It is just streamlit out there

**Comment by Deadshot1611** [comment]
You can only do it after someone works on the fastapi integration with html

**Comment by geekyharsh05** [comment]
@Deadshot1611 Okay
